### ISSUE TITLE
How is SENSEI related to CATALYST?

### ISSUE THREAD

**Issue by wandadars** [Kitware/sensei#2]
Is SENSEI newer than CATALYST? Is it supposed to replaced CATALYST?

**Comment by vibraphone** [comment]
@wandadars Sensei is a layer above Catalyst; it uses Catalyst as one potential destination for in situ data. Sensei also supports libSim, python scripts, ADIOS, libIS, and other backends.

Sorry for the slow reply. It is slow because we use [a different repository's issue tracker](https://gitlab.kitware.com/sensei/sensei/issues) and a [Discourse server](https://discourse.kitware.com/c/sensei) for issues and discussion. Please consider continuing the conversation there.

cc: @burlen
